name: Node.js Multi Environment Deployment

on:
  push:
    branches:
      - dev
      - qa
      - main

jobs:

  # =========================
  # DEV DEPLOYMENT
  # =========================
deploy-dev:
  if: github.ref == 'refs/heads/dev'
  runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to DEV
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.DEV_EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.DEV_EC2_SSH_KEY }}

        script: |
          set -e

          echo "Deploying to DEV..."
          cd /home/ec2-user/my-repo-project2/aws-ec2-cicd-project1

          git fetch origin dev
          git reset --hard origin/dev
          git clean -fd

          echo "2. Checking deployed commit..."
          git rev-parse HEAD
          git log -1 --oneline

          echo "3. Installing dependencies..."
          npm install

          echo "4. Restarting PM2 application..."
          if pm2 describe my-node-app > /dev/null 2>&1; then
            APP_ENV=DEV pm2 restart my-node-app --update-env
          else
            APP_ENV=DEV pm2 start app.js --name my-node-app --update-env
          fi

          pm2 save

          echo "DEV deployment successful!"